services:
  app:
    container_name: story_valut
    image: yiisoftware/yii2-php:8.4-fpm-nginx
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'
    env_file:
      - .env
  database:
    container_name: story_valut_db
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
networks:
  default:
    name: story_valut_network